version: '3.7'

services:
  web:
    build:
      context: ./django_app
      dockerfile: ./deploy/test/Dockerfile
    expose:
      - 8000
    volumes:
      - static_data_test:/app/static/
    env_file:
      - ./django_app/config/test/.env
    command: "gunicorn sgi.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    restart: always
  nginx:
    build:
      context: ./nginx
      dockerfile: ./deploy/test/Dockerfile
    ports:
      - 8000:80
    volumes:
      - static_data_test:/app/static/
    depends_on:
      - web
    restart: always
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    env_file:
      - ./postgres/config/test/.env
    restart: always

volumes:
  postgres_data_test:
  static_data_test:
