version: '3.7'

services:
  web:
    build:
      context: ./django_app
      dockerfile: ./deploy/dev/Dockerfile
    volumes:
      - ./django_app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./django_app/config/dev/.env
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./postgres/config/dev/.env

volumes:
  postgres_data_dev:
